### ISSUE TITLE
Long declaration not correctly formated

### ISSUE THREAD

**Issue by aju** [prettier/stylelint-prettier#144]
**What version of `stylelint`, `prettier` and `stylelint-prettier` are you using?**
styleline: 13.8.0
prettier: 2.2.1
**Please paste any applicable config files that you're using (e.g. `.prettierrc` or `.stylelintrc` files)**
none
**What source code are you linting?**
https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAjCATAngAmAHShxwFoB3OVAawEsYT0APEgZwAsBDDCMpHABgE4AbhwBOAChIkA4gHUSAIQDyADRIBlABIBBACLKFygKoAVAKIAlEgCYSl-QEljGgJQCANCPFTZCgMLKADLK1iqWelauANyEAL6EIB4gEAAOMDTQLMig4mI8AAriCNkoHAA2ZBxY2cmoYhxgVHAwGqmNNFAA5sgwYgCucMlwALaocBgYE0Ec3f0cXXAAYhBiIxwwGd3IIBz9MBBJIGwwI+VybHRwLO1gcBoldDTCdFg7YCy1IJ0scGIwBQaXXWyAAZhVfskAFYsRiKBpNFoaDgjOBBTpwMEQoYgGGMDSdLrlOAARX6EHgWPKkJA7TEvzEOxYHy+qTEnRgchoGBgbGQAA5+Mk2RBfnIGqkdmzrn9hJjkgBHcnwQFpUq7FgkKBwCYTI5iOBKmgGwELEFIcHUnG-EY0XoDa2E4lkimYi3Y5IwDioLk8vlIGyeho0cqE-wQEbmkDXACsR36v1M3tKlppwkGjigU1gGjA7PSOizGhgWGJVN+cTiQA

**What did you expect to happen?**
No errors from stylelint
**What actually happened?**
Error shown:
https://stylelint.io/demo#N4Igxg9gJgpiBcIBG0CeACYAdAdu9AtAO4xIDWAlgC4EoAeBAzgBYCGUER86ADL+gDdWAJwAUBAgHEA6gQBCAeQAaBAMoAJAIIARBbIUBVACoBRAEoEATATM6AkgdUBKXgBpc+fELESZBAMIKADIKFopm2uZOANy4AL64IK4gjKg4VKx0CClgjIxJ4BA4AGYUAObZ2HjoWCDCAK4ANjCMtdxVnjUgrDQNzQQ4EAT1OGSDRDht6FQNMO7V+LVIjRBgZANDMAC2AA5UqFMz9XMenrWQK8IbBBQ4Qo0UUATMMHSHs-Od5xBbWzDp122ewOCGmH1OixAsDAjREPQoRVoKzW1yg9R2DzAPRgBB2wggOxgwioFBaUwA2hDPEcTgtPB1OmcQOVBsIYBSqYyupAcIwYGB6iSBDi0RiKFiqC1iNRmAQoBRisUif8aPdjq0QJzPABdLUJOnaz5M6Gw4TwxHLVbrQZMZgQYlsHBPPEEon7AgQYXCYSPMmgmlGyHFIo0YqsLYURqoVHozHYgbhv3cANU2rBgFhiNR64RvK3MoEMr-InigiZyPRsgwVBEe1Qd7HQNdYojMAkxFYxpga63e6PBu0r4gFs4NsInAETvdm0jRg7VhgGBPV1mqj2gdNtOt9sTh44GAiQtm+Uq66DXkZJ0iJ7ytljoob1MgKuoYpmv5y-mm80Tm0UXb2peVCPnStR-PKrBlgeVD1GyCYfjOozjJM-rgqBIA2rAjCLk6+ZMISYAKuK1AgsmaFDphsbivGPQ3ABxIEH0SZgo2T6UWKEo4nyzRtvaGpkax6E2kC7qMBAsGLiBFGbHQMyQXyEYXEU-EsYOTJ-ncrAPDe4nLFxsIsJOPx-OkKkpuhLqEsS0aIWMnAoQJamQtx-JrlcOx8vUHCTgZjDXCMdkTFJTIubx7med5MDNCZNC2chwXOVFrn2gQ+yEv5SH2QlXSMDMeE2vuRB7uyqGCUOIzUBlgUOapm7dL0TQ4iJ0bFbQMDBmyHJ0pCWlEKwqAak2+AMlytSvIuexdVyQ6WmszR5AQrDFJKVyMIm8E4rNZDzYNWpDqUwi5QMLSSvWmrdTqQ1Miy9oldwlIXUOS0rUZvwqrUe3oLqF36p0hpPrRTEbZOrB8lMtQrCQwi1HVgONcDc4Ljiz1EuD3SNH1A1MPm-TFTDAMNf0CnihAKy-jARW3Mjy2o6CtS9f1u3oVtPkQIweFIGai4EM1BCtUg7W3Wj+5evjzPIusMJsxzXM4oVrUo9DdPo5jTMzRLrPszgBac0jx2U-ubUdXdXQM1jWxNCSfNU2L6tWprMt64j3MC8baNm35WtlLjNtJE+LOujgjvc-LVOLTTSvcPTGOMwQFuNFbeN++L9uB8HXHztzivuzHWNez7+620yAeEkH2u0LL+F667QvKx7ReQkpVwvAwWJg8rkO03VTfPK8fP-GUVDMGjLCAQ33LGaevP84LnWgg9o0q4z4-DZ9Y10BNwHz59QYUIdsUnUuH2PV9V2Qjdc-3TvOX7M0e40JAvysE6Gqfd9XK-ZdT6PzFxDMNQLRM44luOzWAOdVbj3OPUXKPxcT4isu6aeYca6X3QAvRk0cIHJy5CNDBIBxowEmtvE+PUI6TmgWuLYcCVz7BXngg6R19y5SPudaap817MjKKyE26C2H0zIT-d62C2FdBAb6bG2sC6bQlsfNh79GSf3wP9dCJo4Q7loM-AsztqYrWFjAUWwjISqNXOODR5dtFG1rlHJeA1IFQi-Go0xLNiZKXJgbHRtNrEezjpbCg1tC6GK6MYn8SJ7YuNJoiCx2c66509jjHESc6rBPUc47YJMyZVxdrPE2tQRZdyfMkpxGt84JLDlsTIn4YSOOUlMAAjEkhxJiLQazkpGPC4SybgOXoE2ohSOwRLcQrCOXTza+P8SVBpVSmkTlcZkjxkdTaxIkd7UpATJnfnUbMixKCckYX0fklRjSQlIMNjsqaeD66BNXifdem9zl8O6GQvpKEz5MgYQfZhZ036vNqBfHh19+EvUEekOhQ4xGwGWVI0JaxZHTXkZ0RR7D0IjnvDM4ykFQ6G2iV4pZ8dE6+zqiizZ6K5nh10TE1WkLVkTKfES0xP95JAMsag3J+ylaEu3KY8pDATnMR4By0c6icDrTbrszu7LaWcsRPONk6QXh8j8pi4BvJfQjL8nivxiTJWCtMTKlU8qpQWPBbsvJq14njLsXSxERB-6SiicMil3S6q3FgOkH8UxLB1WaNrIeBAABeRIhiIWoNlMCFTeUqXqU+cCFBIJKh6LBHEWymXYsWVguqMa43QUTUZDJ2zsl6IMRmpcsaoIJrgsKj8oq0birsZmstME4J6rlS0Q1TLjWFoOUOet8bG04jNNrHEK4egpXteSnF6bo0lqzeW-tmih1WRHatJlZzHW2J6SAetABHY4wgWoUCOgy-WQzx1ptjhqi1G7t27v3YeklY7PFnrzuarV6Fr1ElvQ-e9K6C3K1NXY4SpM-4AO0aGjCQxcxex5k6D0xQmDiWECHCmSdHJ1RwPULYAsrjNHYHhAN+I1UAYw1h64rS9wFnw2zMDlk3TRmrR3TgXamRA15cy-5F1MHnrGa+nBHCCFEKviQ5se9GGHy+SfZRDy-n3OmoCokr0Yqwq5PCzwiLJMhSSmFRaVA8pIEFJtLmVYqCe3bSqsBf62V2NCm5bTun9MekXTZh9CzWVFqfNZlKPQ7OSgc0SJdpLV3WP-RujzVxH5IFuP55zhGQuaZs+FyLTmf1uzXWrDTPEbNYRwlAZ+X7MOJZSgVSJQCwOhetnep+x6w6ps4+uuqZWHgVfKQF39QXLOxYyylblPNdjumKipfl7m4spQ8jALyQwqkLXo9Y2tHXkrhTG95Sbflm1D1bSZvWHaLNufQmV0b42ebRVPNNros36vDYWwdpKv9ZmDAyDuNGHB6h6Ssxd1KqB0onYhoxiV6EKoP1BmKn7di1Q4hfLWYQTwvsgDO0+UH5W8vNaVWSx9tX1XcYJXDrSxwEcKcZXrGrNi4mSOpSD7HpSmv46ySltrO2hzw8azQbrEapg8FOPqOIIA4hAA

**Comment by BPScott** [comment]
You shouldn't enable stylelint rules that conflict with prettier. This is because prettier's ethos is that [prettier should handle code formatting, while linters should handle code quality](https://prettier.io/docs/en/comparison.html).

You should disable the declaration-colon-newline-after rule. You can use https://github.com/prettier/stylelint-config-prettier to disable all rules that would conflict with prettier. That package also provides a helper tool that lets you identify any rules that you currently have enabled that would conflict with prettier's styling.
