### ISSUE TITLE
Parsing error: Declaration or statement expected.stylelint(prettier/prettier)

### ISSUE THREAD

**Issue by borisyordanov** [prettier/stylelint-prettier#15]
**What version of `stylelint`, `prettier` and `stylelint-prettier` are you using?**
```
        "prettier": "^1.15.3",
        "stylelint": "^9.10.1",
        "stylelint-config-concentric-order": "^3.4.1",
        "stylelint-config-prettier": "^4.0.0",
        "stylelint-config-recommended": "^2.1.0",
        "stylelint-config-styled-components": "^0.1.1",
        "stylelint-prettier": "^1.0.6",
        "stylelint-processor-styled-components": "^1.5.2",
```
**Please paste any applicable config files that you're using (e.g. `.prettierrc` or `.stylelintrc` files)**
`.prettierrc`
```
{
    "singleQuote": true,
    "printWidth": 120,
    "tabWidth": 4
}
```

`.stylelintrc` 
```
{
 "processors": ["stylelint-processor-styled-components"],
  "extends": [
    "stylelint-config-recommended",
    "stylelint-config-styled-components",
    "stylelint-config-concentric-order",
    "stylelint-prettier/recommended"
  ],
  "plugins": ["stylelint-prettier"],
  "rules": {
    "prettier/prettier": true
  }
}
```
**What source code are you linting?**
```const Wrapper = styled.div`
    margin: 0 auto;
`;```
**What did you expect to happen?**

**What actually happened?**
`Parsing error: Declaration or statement expected.stylelint(prettier/prettier)`

Getting this error when running `stylelint` in the terminal and in VSC itself

![image](https://user-images.githubusercontent.com/12392666/52633143-cc252e80-2ec3-11e9-895e-d98a535d9eee.png)

The error does not happen if i use this syntax
```
const Wrapper = styled(Image)`
    margin: 0 auto;
`;
```

**Comment by BPScott** [comment]
stylelint's css-in-js stuff is pretty opaque to me as I've never used it. Would you be able to set up a repo that reproduces this issue that I can clone and go into debugging it immediately without wondering how to setup the css-ins stuff?

**Comment by borisyordanov** [comment]
@BPScott thanks for looking into this.

So i tried making a repot with CRA with vanilla JS (i normally use TS) and got another error.

![image](https://user-images.githubusercontent.com/12392666/52911994-990be200-32ab-11e9-9df9-9c2311e8e167.png)

So i set up two repos (one in JS and one in TS) for each bug.

https://github.com/borisyordanov/prettier-stylelint-styled-components-bug

**Comment by BPScott** [comment]
Thank you for taking the time to try and make a minimal reproduction.

> I also learned that i can only reproduce this bug if i have the [stylelint VSC extension](https://github.com/shinnn/vscode-stylelint)

Does that mean running `stylelint` over your files on the command line works without errors (both passing when there are no errors, and correctly reporting errors if they are present)? If that is the case then it sounds like this is an issue with the stylelint VSCode extension rather than stylelint-prettier

**Comment by borisyordanov** [comment]
> Does that mean running `stylelint` over your files on the command line works as expected

I get the same errors when i run `stylelint` in a terminal as well. 

I was just explaining how you can reproduce the bug from the screenshot, because it shows VSC and not a command line.

**Comment by arvigeus** [comment]
If you have in same file
```js
const Wrapper = styled.div`
  margin: 0 auto;
`

const Root = styled.div`
  width: 100%;
`
```
Only the first instance gets reported.

If you only care about prettifying your styles and nothing else, just use `stylelint-config-prettier`.  Then you need `prettier-stylelint` installed and `"prettier.stylelintIntegration": true` in your `.vscode/settings.json` file.

**Comment by BPScott** [comment]
#22 changes stylelint-prettier so we skip trying to format sections of code within css-in-js blocks with prettier. You're almost certainly about to run prettier over the whole file anyway so duplicating that linting work feels pointless
