### ISSUE TITLE
stylelint: Could not find "stylelint-config-prettier". Do you need a `configBasedir`?

### ISSUE THREAD

**Issue by 7mouse** [prettier/stylelint-prettier#162]
This is in my package.json
```json
{
  "devDependencies": {
    "prettier": "^2.2.1",
    "stylelint": "^13.11.0",
    "stylelint-config-prettier": "^8.0.2",
    "stylelint-config-standard": "^20.0.0",
    "stylelint-prettier": "^1.2.0",
    }
}
```

This is my .stylelintrc.json
```json
{
  "extends": ["stylelint-config-standard", "stylelint-prettier/recommended"],
  "plugins": ["stylelint-prettier"],
  "rules": {

  }
}
```

in vscode throw error:
stylelint: Could not find "stylelint-config-prettier". Do you need a `configBasedir`?

**Comment by shih-js** [comment]
@7mouse, were you able to resolve this issue? I am running into the same thing.

**Comment by TimRChen** [comment]
try to remove stylelint-config-standard.
```json
{
  "extends": ["stylelint-prettier/recommended"],
  "plugins": ["stylelint-prettier"],
  "rules": {
    "prettier/prettier": true
  }
```

**Comment by bigbigDreamer** [comment]
> @7mouse, were you able to resolve this issue? I am running into the same thing.

#https://github.com/myNameIsDu/aktiv/pull/81

**Comment by pioz** [comment]
Same problem here.

**Comment by Nicolas-Aguila** [comment]
Deben especificar la ruta donde se va a correr y sobre que archivos:

`   npx stylelint src/**/*.scss --fix  `

Ese comando, en mi caso funciona.
