### ISSUE TITLE
[feature request] include properties order rules

### ISSUE THREAD

**Issue by wujekbogdan** [prettier/stylelint-prettier#17]
IMO it would be good if stylelint-pretier had rules for css properties order. Here's a quite good example of the properties hierarchy: https://9elements.com/css-rule-order/

**Comment by evilebottnawi** [comment]
I think it is out of scope this project

**Comment by wujekbogdan** [comment]
> I think it is out of scope this project

Why? Or maybe - what is the scope of this project?

**Comment by BPScott** [comment]
The scope of this project is to apply prettier's rules. Prettier's ethos is centred around providing [consistent formatting rules](https://prettier.io/docs/en/comparison.html) and deliberately says nothing about code quality stuff like the ordering of properties in CSS.

If you want to do have opinions about ordering of css declarations then I suggest looking into [stylelint-order](https://github.com/hudochenkov/stylelint-order) which can happily be used in conjunction with stylelint-prettier (as I use them together in my work configs).

**Comment by wujekbogdan** [comment]
@BPScott 
Got it. Thanks for the explanation.
