### ISSUE TITLE
Seeing a lot of "Insert line break" errors

### ISSUE THREAD

**Issue by muuvmuuv** [prettier/stylelint-prettier#196]
**What version of `stylelint`, `prettier` and `stylelint-prettier` are you using?**

```
    "prettier": "^2.3.2",
    "stylelint": "^13.13.1",
    "stylelint-config-prettier": "^8.0.2",
    "stylelint-config-recess-order": "^2.5.0",
    "stylelint-config-recommended-scss": "^4.2.0",
    "stylelint-config-standard": "^22.0.0",
    "stylelint-order": "^4.1.0",
    "stylelint-prettier": "^1.2.0",
    "stylelint-scss": "^3.19.0",
```

**Please paste any applicable config files that you're using (e.g. `.prettierrc` or `.stylelintrc` files)**

I have also tried disabling all other configs, same error.

```json
{
  "proseWrap": "always",
  "printWidth": 90,
  "semi": false,
  "trailingComma": "all"
}
```

```json
{
  "extends": [
    "stylelint-config-standard",
    "stylelint-config-recommended-scss",
    "stylelint-config-recess-order",
    "stylelint-prettier/recommended"
  ],
  "rules": {
    "selector-type-no-unknown": [
      true,
      {
        "ignoreTypes": [
          "/^ion-/"
        ]
      }
    ]
  }
}
```

**What source code are you linting?**

```scss
.fullHeight,
[full-height] {
  height: 100%;
}
```

but it is applied to everything so it's not specific to one code part.

**What did you expect to happen?**

No errors

**What actually happened?**

```
   5:46  ✖  Insert "␍"                                 prettier/prettier            
   6:43  ✖  Insert "␍"                                 prettier/prettier            
   7:50  ✖  Insert "␍"                                 prettier/prettier            
   8:50  ✖  Insert "␍"                                 prettier/prettier            
   9:55  ✖  Insert "␍"                                 prettier/prettier            
  10:46  ✖  Insert "␍"                                 prettier/prettier            
  11:43  ✖  Insert "␍"                                 prettier/prettier            
  12:1   ✖  Insert "␍"                                 prettier/prettier      
```

**Comment by BPScott** [comment]
It sounds like somehow something wants to use [windows-style line endings](https://prettier.io/docs/en/options.html#end-of-line). In this case it seems like the plugin is doing everything correctly but you've misconfigured it somehow.

This formatting comes from prettier. This plugin doesn't have any opinion about formatting itself, it just passes along prettier's style. If you believe prettier's formatting should be changed then you should open an issue in the prettier repository: https://github.com/prettier/prettier
