### ISSUE TITLE
CR at End Of File

### ISSUE THREAD

**Issue by rzontar** [prettier/stylelint-prettier#23]
When formatting css files on Windows we ran into a problem where the Files terminated with CR and not CRLF as excepted. We set the prettier Option `endOfLine` to `"crlf"` explicitly, but the problem persisted. 

**What version of `stylelint`, `prettier` and `stylelint-prettier` are you using?**
stylelint 10.0.1
prettier 1.17.1
stylelint-prettier 1.1.0 (tested with 1.0.7 as well)

**Please paste any applicable config files that you're using (e.g. `.prettierrc` or `.stylelintrc` files)**
I made a minimal sample to reproduce the error:
https://github.com/rzontar/stylelint-prettier-cr

**What source code are you linting?**
CSS

**What did you expect to happen?**
Running `stylelint --fix .\test.css` 
should format line 6 as `}CRLF`

**What actually happened?**
Running `stylelint --fix .\test.css`
formats line 6 as `}CR`

But running prettier standalone produces correct results.
`prettier --write .\test.css`

**Comment by BPScott** [comment]
Fixed in #24
