### ISSUE TITLE
Delete "␍" (prettier/prettier)

### ISSUE THREAD

**Issue by JanBergsma** [prettier/stylelint-prettier#285]
**What version of `stylelint`, `prettier` and `stylelint-prettier` are you using?**

**Please paste any applicable config files that you're using (e.g. `.prettierrc` or `.stylelintrc` files)**

**What source code are you linting?**

**What did you expect to happen?**

**What actually happened?**

**Comment by BPScott** [comment]
This is not an issue with the plugin. This is prettier telling you that you've got a cartridge return `\r` somewhere but prettier wants to format newlines with just `\n`.

**Comment by JanBergsma** [comment]
Yes, thanks!
