### ISSUE TITLE
Support prettier v3

### ISSUE THREAD

**Issue by JounQin** [prettier/stylelint-prettier#298]

**Comment by kuoruan** [comment]
```
"prettier.resolveConfig.sync is not a function"
```

After update to prettier v3

**Comment by carlosjeurissen** [comment]
"prettier.resolveConfig.sync" has been removed by Prettier. As can be read here:
https://github.com/prettier/prettier/pull/12788

The synchronous methods for Prettier have been removed. With only Async methods left.

This means `stylelint-prettier` needs to be updated to become an async stylelint plugin. More info about this can be found here:
https://github.com/stylelint/stylelint/blob/main/docs/developer-guide/plugins.md#asynchronous-rules

**Comment by websitevirtuoso** [comment]
yes. waiting new release

**Comment by BPScott** [comment]
I hear y'all loud and clear. I'll be dealing with this up date over the next few days.

**Comment by BPScott** [comment]
`stylelint-prettier` v4.0.0 has been released, with support for Prettier v3.0.0, but it has dropped support for prettier v2 at the same time. 

When you update prettier to v3.0.0, make sure you update `stylelint-prettier` v4.0.0 at the same time.

You must also ensure that you're using at least `stylelint` v15.8.0 too, as earlier versions  included v8-compile-cache, which did not place nice prettier v3's esm only behaviour as it caused segmentation faults.

**Comment by websitevirtuoso** [comment]
awesome
