### ISSUE TITLE
`Parsing error: Unexpected token` when used with `stylelint-config-html`

### ISSUE THREAD

**Issue by arty-name** [prettier/stylelint-prettier#332]
**What version of `stylelint`, `prettier` and `stylelint-prettier` are you using?**

```
    "prettier": "^3.0.3",
    "stylelint": "^15.10.3",
    "stylelint-prettier": "^4.0.2"
```

**Please paste any applicable config files that you're using (e.g. `.prettierrc` or `.stylelintrc` files)**

Here’s [a minimal reproduction on StackBlitz](https://stackblitz.com/edit/github-3g2dsc?file=package.json)

.prettierrc
`{ "plugins": ["prettier-plugin-astro"] }`

.stylelintrc.json
```json
{
  "extends": [
    "stylelint-config-standard",
    "stylelint-config-html",
    "stylelint-prettier/recommended"
  ]
}
```

**What source code are you linting?**

An Astro page:
`<html lang="en"><body><style>body { color: red }</style></body></html>`

**What did you expect to happen?**

The file should be parsed and linted

**What actually happened?**

```
src/pages/index.astro
 1:39  ✖  Parsing error: Unexpected token, expected "}"  prettier/prettier

1 problem (1 error, 0 warnings)

**Comment by mattlyons0** [comment]
You can mitigate this for now by switching to my fork with #340 in it with `npm install --save-dev "mattlyons0/stylelint-prettier#mlyons/astro" `
