### ISSUE TITLE
Unknown rule prettier/prettier

### ISSUE THREAD

**Issue by icy0307** [prettier/stylelint-prettier#339]
**What version of `stylelint`, `prettier` and `stylelint-prettier` are you using?**
stylelint:15.11.0
prettier:2.8.8
stylelint-prettier:4.0.2
**Please paste any applicable config files that you're using (e.g. `.prettierrc` or `.stylelintrc` files)**
.stylelintrc
``` json
{
  "extends": [
    "stylelint-config-standard-scss",
    "stylelint-prettier"
  ],
  "rules": {
    "prettier/prettier": true
  }
}
```
**What source code are you linting?**

``` scss
a+ b { color: pink; }
```
**What did you expect to happen?**

Expected single space before "+"
**What actually happened?**
✖  Unknown rule prettier/prettier                          prettier/prettier

**Comment by BPScott** [comment]
[Please read the installation instructions](https://github.com/prettier/stylelint-prettier?tab=readme-ov-file#installation).

You want either:
```
{
  "plugins": ["stylelint-prettier"],
  "rules": {
    "prettier/prettier": true
  }
}
```

or 
```
{
  "extends": ["stylelint-prettier/recommended"]
}
```
