### ISSUE TITLE
Switch deprecated `github` formatter to another formatter in test suite

### ISSUE THREAD

**Issue by ybiquitous** [prettier/stylelint-prettier#365]
Hello, 👋🏼 

I'm a maintainer of Stylelint. Let me notify you that the `stylelint-prettier` test suite is broken with the next Stylelint 16.8.0 because it's using the deprecated `github` formatter.

See the relevant pull request https://github.com/stylelint/stylelint/pull/7865 and the following test code:
https://github.com/prettier/stylelint-prettier/blob/8d76b2c1145a98d0e52a438e7e44c15599fddcdb/test/stylelint-prettier-e2e.test.js#L112-L113

You can see test results with the Stylelint edge version here:
https://github.com/stylelint/stylelint-ecosystem-tester/actions/runs/10133293105/job/28018291989

So, I recommend switching `github` to another stable formatter, for example `json`.
Thanks.

**Comment by Mouvedia** [comment]
You could try to replace

https://github.com/prettier/stylelint-prettier/blob/8d76b2c1145a98d0e52a438e7e44c15599fddcdb/package.json#L24C5-L24C59

by

```json
    "test": "yarn run lint && node --test --no-deprecation test/*.test.js",
```

ref https://github.com/nodejs/node/blob/01cf9bccdfa7fb31a8a1d91ae45e594a730e0427/lib/internal/process/warning.js#L179

**Comment by BPScott** [comment]
Thanks for the ping @ybiquitous.

Ironically I started using the github formatter in the e2e tests as I hoped its output would be more consistent between versions than the default formatter, as I found cases where the default formatter changed slightly between stylelint versions (mostly adjusting whitespace) and caused my e2e tests to fail.

I've switched over to use the json formatter.

**Comment by ybiquitous** [comment]
Thank you!

**Comment by Mouvedia** [comment]
> Please let me know if if the ecosystem tests are still broken after this change.

They are since https://github.com/stylelint/stylelint-ecosystem-tester/actions/runs/11675534073.

**Comment by ybiquitous** [comment]
This looks like another cause than the `github` formatter. It'd be better if we could open a new issue.
