### ISSUE TITLE
Error thrown on files that has no associated parser (even when specifying it explicitly)

### ISSUE THREAD

**Issue by sneridagh** [prettier/stylelint-prettier#37]
**What version of `stylelint`, `prettier` and `stylelint-prettier` are you using?**
    "prettier": "1.19.1",
    "stylelint": "11.1.1",
    "stylelint-prettier": "1.1.1",

**Please paste any applicable config files that you're using (e.g. `.prettierrc` or `.stylelintrc` files)**
```
  "prettier": {
    "trailingComma": "all",
    "singleQuote": true
  },
  "stylelint": {
    "extends": ["stylelint-config-idiomatic-order"],
    "plugins": ["stylelint-prettier"],
    "rules": {
        "prettier/prettier": true
      }
  },
```
**What source code are you linting?**

test.overrides
```
a {
  color: red;
}
```
**What did you expect to happen?**
I'm using the CLI, and the error is also observable on VSCode. I run stylelint on a file that has an extension that does not match one of the supported parsers like:

test.overrides
```
a {
  color: red;
}
```
Then launch the command:
`./node_modules/.bin/stylelint test.overrides --syntax less`

**What actually happened?**
Fails with:
```
Error: No parser could be inferred for file: /Users/sneridagh/Development/plone/volto/test
    at normalize$1 (/Users/sneridagh/Development/plone/volto/node_modules/prettier/index.js:9798:15)
    at formatWithCursor (/Users/sneridagh/Development/plone/volto/node_modules/prettier/index.js:13525:12)
    at /Users/sneridagh/Development/plone/volto/node_modules/prettier/index.js:44207:15
    at Object.format (/Users/sneridagh/Development/plone/volto/node_modules/prettier/index.js:44226:12)
    at /Users/sneridagh/Development/plone/volto/node_modules/stylelint-prettier/stylelint-prettier.js:101:35
    at performRules.push.Promise.all.postcssRoots.map (/Users/sneridagh/Development/plone/volto/node_modules/stylelint/lib/lintSource.js:223:8)
    at Array.map (<anonymous>)
    at rules.forEach (/Users/sneridagh/Development/plone/volto/node_modules/stylelint/lib/lintSource.js:219:18)
    at Array.forEach (<anonymous>)
    at lintPostcssResult (/Users/sneridagh/Development/plone/volto/node_modules/stylelint/lib/lintSource.js:183:8)
```
When not using prettier in the middle, stylelint works as expected, without even specifying the parser (which also fails). On supported file extensions it works well.

**Comment by BPScott** [comment]
Setting the parser on the command line will set stylelint's parser but this won't get passed through to prettier.

You can teach Prettier to use a particular parser for a file extension it does not already know about by using [configuration overrides](https://prettier.io/docs/en/configuration.html#configuration-overrides).

Adding the following to your .prettierrc should tell it to use the less parer for .overrides files

```json
{
  "overrides": [
    {
      "files": "*.overrides",
      "options": { "parser": "less" }
    }
  ]
}
```

**Comment by sneridagh** [comment]
Thanks @BPScott I just tried it and this is what the vscode prettier console throws:
```
[INFO - 9:33:24 AM] File Info:
{
  "ignored": false,
  "inferredParser": null
}
[WARN - 9:33:24 AM] Parser not inferred, using VS Code language.
```

**Comment by BPScott** [comment]
That doesnt seem like any logging in stylelint-prettier, it seems like it's from some vscode plugin. Does this work if you run stylelint from the command line?

**Comment by BPScott** [comment]
I'm fairly sure that VSCode warning is the result of an absent (but easily added) option when looking up the parser - https://github.com/prettier/prettier-vscode/issues/1067

**Comment by BPScott** [comment]
Hi @sneridagh,

Can you please confirm if:

- Adding the overrides section works when you try and run stylelint from the command line
- Adding the overrides section works when you try and format using prettier 1.19.0 and a prettier-vscode version newer than v3.7.0 (which should include a fix for that `inferredParser` being null despite your overrides).

**Comment by sneridagh** [comment]
@BPScott 

My config as you suggested:
```
  "prettier": {
    "trailingComma": "all",
    "singleQuote": true,
    "overrides": [
      {
        "files": "*.overrides",
        "options": {
          "parser": "less"
        }
      }
    ]
  },
```

* Using the command line:
`$ ./node_modules/.bin/stylelint 'theme/**/*.overrides' 'src/**/*.overrides'`

```
theme/extras/custom.overrides
 31:3  ✖  Unknown word   CssSyntaxError
```

`$ ./node_modules/.bin/stylelint --syntax less 'theme/**/*.overrides' 'src/**/*.overrides'`
No errors

* Using prettier-vscode 3.11.0 the problem still is present on saving *.overrides files:

```
["INFO" - 10:21:14 AM] Formatting /Users/sneridagh/Development/kitconcept/bundesrechungshof/theme/extras/custom.overrides
["INFO" - 10:21:14 AM] Loaded module 'prettier@1.19.1' from '/Users/sneridagh/Development/kitconcept/bundesrechungshof/node_modules/prettier/index.js'
["INFO" - 10:21:14 AM] Using ignore file (if present) at /Users/sneridagh/Development/kitconcept/bundesrechungshof/.prettierignore
["INFO" - 10:21:14 AM] File Info:
{
  "ignored": false,
  "inferredParser": null
}
["WARN" - 10:21:14 AM] Parser not inferred, using VS Code language.
["INFO" - 10:21:14 AM] Loaded module 'prettier@1.19.1' from '/Users/sneridagh/Development/kitconcept/bundesrechungshof/node_modules/prettier/index.js'
["INFO" - 10:21:14 AM] Resolved parser to 'less'
["INFO" - 10:21:14 AM] Detected local configuration (i.e. .prettierrc or .editorconfig), VS Code configuration will not be used
["INFO" - 10:21:14 AM] Prettier Options:
{
  "filepath": "/Users/sneridagh/Development/kitconcept/bundesrechungshof/theme/extras/custom.overrides",
  "parser": "less",
  "trailingComma": "all",
  "singleQuote": true
}
```

Hope that's useful.

**Comment by BPScott** [comment]
`./node_modules/.bin/stylelint 'theme/**/*.overrides' 'src/**/*.overrides'` throwing an error is expected - you've told prettier that `.overrides` files should be parsed as less files, but you never told stylelint that - which is why adding `--syntax less` works.

`./node_modules/.bin/stylelint --syntax less 'theme/**/*.overrides' 'src/**/*.overrides'` works which means that any issue you're having is not with stylelint-prettier. 

Any issues with prettier-vscode should be raised in their repo, though it looks like it eventually resolves the correct parser.

---

It's not quite the fix you're hoping for but in my experience files without their common extensions result only in pain when trying to get tooling to work with them. Would renaming your file from `custom.overrides` to `custom.overrides.less` be the end of the world?
