### ISSUE TITLE
Crashes when autofixing with syntax specified (root.source.syntax is undefined) such as when running stylelint via Atom

### ISSUE THREAD

**Issue by lydell** [prettier/stylelint-prettier#8]
<strong>TL;DR https://github.com/prettier/stylelint-prettier/issues/8#issuecomment-426897632</strong>

**What version of `stylelint`, `prettier` and `stylelint-prettier` are you using?**

stylelint: 9.6.0
prettier: 1.13.7
stylelint-prettier: 1.0.3

**Please paste any applicable config files that you're using (e.g. `.prettierrc` or `.stylelintrc` files)**

Default Prettier settings, `"prettier/prettier": true` for stylelint.

**What source code are you linting?**

```scss
a {
  color:red;
}
```

**What did you expect to happen?**

A space to be inserted before `red`.

**What actually happened?**

An error was thrown.

This line fails when running stylelint via linter-stylelint (from this PR which has autofix support: https://github.com/AtomLinter/linter-stylelint/pull/385):

https://github.com/prettier/stylelint-prettier/blob/0782dce0e0f8bb86bfa9589e5669e243937238f6/stylelint-prettier.js#L122

```
TypeError: Cannot read property 'parse' of undefined
    at /home/lydell/5m/doowin-site/node_modules/stylelint-prettier/stylelint-prettier.js:122
```

At first I thought it was due that linter-stylelint PR using an older version of stylelint (9.2.0), but I upgraded to 9.6.0 here and it still happens: https://github.com/lydell/linter-stylelint (`apm install lydell/linter-stylelint`)

I quickly looked over the PostCSS docs and couldn’t find anything about the `.syntax` property – do you know where it comes from, and why it could be missing when running in Atom? It works fine when running from the command line. EDIT: I've now grepped through the PostCSS, stylelint and stylelint-prettier repos and can't find any obvious references to source.syntax

I know it’s super annoying to get issue reports that involve an editor you might not use – even worse when specific PRs of editor plugins – but I’m putting this out here since I got a bit stuck in my debugging for now and what to see if anyone has any ideas.

**Comment by lydell** [comment]
`root.opts.syntax` does exist and works in Atom, but unfortunately it seems to contain the CSS parser, not the "current" parser:

```
main/css/global.scss
 131:3  ✖  Unexpected unknown property "//"      property-no-unknown             
 131:3  ✖  Unexpected double-slash CSS comment   no-invalid-double-slash-comments
 137:3  ✖  Unexpected unknown property "//"      property-no-unknown             
 137:3  ✖  Unexpected double-slash CSS comment   no-invalid-double-slash-comments
```

In the above example, SCSS comments were treated like CSS properties.

**Comment by BPScott** [comment]
I believe root.source.syntax is being added by the [postcss-syntax](https://github.com/gucong3000/postcss-syntax) plugin (which allows the dynamic changing of what postcss plugin you use which allows stylelint to jump between css/scss/etc syntaxes.

stylelint-prettier doesn't work with stylelint 9.2.0, but does work with 9.2.1. You can prove this by checking out stylelint-prettier, modifying the devDependency on stylelint changing "^9.2.1" to "9.2.0", running `yarn install` then `yarn test` - it gives a "Cannot read property 'parse' of undefined" error on the `root.source.syntax.parse...` line, the same as the error you are experiencing.


That leads me to think your update of stylelint within linter-stylelint did not work as you had expected. Perhaps some transitive dependencies didn't get pulled in as expected or you need to reinstall the atom plugin / restart atom for the dependency change to take effect?

**Comment by lydell** [comment]
> That leads me to think your update of stylelint within linter-stylelint did not work as you had expected.

I also noticed that 9.2.0 doesn't work while 9.2.1 does. And my first thought was also that the update didn't work out. But I've spent a lot of energy on verifying that. I've purged the plugin, re-installed it again, deleted Atom cache and compile cache, worked with the debugger in Atom, done `require("stylelint").version`… with no success.

> Perhaps some transitive dependencies didn't get pulled in as expected

Good idea! I'll try that out.

**Comment by lydell** [comment]
No luck so far with double-checking transitive dependencies.

You are right about it being postcss-syntax that sets root.source.syntax. Thanks! However, it seems like it is not safe to rely on root.source.syntax always existing, because stylelint only runs postcss-syntax in a conditional:

https://github.com/stylelint/stylelint/blob/master/lib/getPostcssResult.js#L91

**Comment by BPScott** [comment]
It looks like root.source.syntax doesn't get setup when you pass in a custom syntax.

As I'm a VSCode guy so in a bid to help debug this would you mind letting me know what options get passed into stylelint when it runs this line on a problematic file: https://github.com/AtomLinter/linter-stylelint/blob/master/lib/index.js#L233

Adding a `console.log(options)` on the line above should be sufficient. Hopefully that can give me enough info that I can try and reproduce this using the stylelint API/CLI

**Comment by lydell** [comment]
Thanks, I'll try that out later today.

Btw, to reproduce the issue with the CLI, all you need to do is to pass `--syntax scss`:


```
❯ stylelint main/css/global.scss --syntax scss --fix
TypeError: Cannot read property 'parse' of undefined
    at /home/lydell/test/node_modules/stylelint-prettier/stylelint-prettier.js:124:44
    at Promise.resolve.then (/home/lydell/test/node_modules/stylelint/lib/lintSource.js:221:9)
    at <anonymous>
```

**Comment by lydell** [comment]
Here's the result of that `console.log` you asked for:

```js
{
  "code": "*, *::before, *::after {\n  box-sizing: border-box; ......",
  "codeFilename": "/home/lydell/test/main/css/global.scss",
  "fix": false,
  "syntax": "scss",
  "disableDefaultIgnores": true,
  "config": {...},
  "configBasedir": "/home/lydell/test"
}
```

Since `"syntax": "scss"` is set, I guess stylelint ends up in the following if-branch, causing postcss-syntax never to be run:

https://github.com/stylelint/stylelint/blob/a70058f08d5fe1ded44d333a10486e06a05adc54/lib/getPostcssResult.js#L77
